import React, { useState } from "react";
import "./Project.css";
import { 
    faHtml5,
    faReact,
    faCss3,
    faBootstrap,
    faJs,
} from "@fortawesome/free-brands-svg-icons";
import {
    faCircleArrowDown
  } from "@fortawesome/free-solid-svg-icons";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

function Projects() {
    return (
        <div className="container1">
            <div className="container2">
                <div className="title1">
                <h1>Projects</h1>
                </div>
                <div className="cardslist">
                    <div className="card card1">
                        <div className="head1"><h1>Portfolio Website</h1></div>
                        <div className="desc1">My personal portfolio website, built with React, HTML, CSS, Bootstrap, and JavaScript, showcases my skills and projects in a visually appealing and responsive design for an engaging user experience.</div>
                        <div className="techstack">
                            <FontAwesomeIcon icon={faHtml5}  className="techstack"/>
                            <FontAwesomeIcon icon={faCss3}  className="techstack"/>
                            <FontAwesomeIcon icon={faBootstrap}  className="techstack"/>
                            <FontAwesomeIcon icon={faReact}  className="techstack"/>
                            <FontAwesomeIcon icon={faJs}  className="techstack"/>
                        </div>
                        <button className="link1"><a href="https://raja-rk.github.io/Weather-APP/" target="_blank">-go-</a></button>
                    </div>
                    <div className="card card2">
                        <div className="head1"><h1>Weather App</h1></div>
                        <div className="desc1">Introducing a weather app website that displays real-time data for any location. Built with HTML, CSS, and JavaScript, it utilizes Fetch API to retrieve weather information from the OpenWeatherMap API, providing up-to-date weather conditions in a user-friendly interface.</div>
                        <div className="techstack">
                            <FontAwesomeIcon icon={faHtml5}  className="techstack"/>
                            <FontAwesomeIcon icon={faCss3}  className="techstack"/>
                            <FontAwesomeIcon icon={faBootstrap}  className="techstack"/>
                            <FontAwesomeIcon icon={faJs}  className="techstack"/>
                        </div>
                        <button className="link1"> <a href="https://raja-rk.github.io/Weather-APP/" target="_blank">-go-</a></button>
                    </div>
                    <div className="card card3">
                        <div className="head1"><h1>Payroll Mgt. system</h1></div>
                        <div className="desc1">The Employee Payroll Management System is a database management project built using MySQL and SQL. It provides an efficient solution for managing employee payroll information, ensuring accurate calculations and streamlined record-keeping.
                        </div>
                        <span className="techstack3">Tech Stack: MySQl ,SQL</span>
                        <button className="link1"><a href="https://github.com/raja-rk/Payroll-management-system" target="_blank">-go-</a></button>
                    </div>
                    <div className="card card4">
                        <div className="head1"><h1>Simon Game</h1></div>
                        <div className="desc1">Welcome to the Simon Game! This interactive website is built using HTML, CSS, and JavaScript. Test your memory skills by repeating the sequence of colors generated by Simon in this classic memory game. Enjoy the challenge and have fun!</div>
                        <div className="techstack">
                            <FontAwesomeIcon icon={faHtml5}  className="techstack"/>
                            <FontAwesomeIcon icon={faCss3}  className="techstack"/>
                            <FontAwesomeIcon icon={faJs}  className="techstack"/>
                        </div>
                        <button className="link1"><a href="https://github.com/raja-rk/simon-game" target="_blank">-go-</a></button>
                    </div>

                </div>
                {/* <FontAwesomeIcon icon={faCircleArrowDown}  className="downarrow"/> */}
            </div>
        </div>
    );
}

export default Projects;
